In [57]:
import numpy as np

In [58]:
import pandas as pd

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df = pd.read_csv("E:/finalyearproject_dataset/KDDTrain+.txt/KDDTrain+.txt")


In [61]:
df

0  tcp  ftp_data   SF   491   0.1  0.2  0.3  0.4  0.5  ...  0.17  \
0       0  udp     other   SF   146     0    0    0    0    0  ...  0.00   
1       0  tcp   private   S0     0     0    0    0    0    0  ...  0.10   
2       0  tcp      http   SF   232  8153    0    0    0    0  ...  1.00   
3       0  tcp      http   SF   199   420    0    0    0    0  ...  1.00   
4       0  tcp   private  REJ     0     0    0    0    0    0  ...  0.07   
...    ..  ...       ...  ...   ...   ...  ...  ...  ...  ...  ...   ...   
125967  0  tcp   private   S0     0     0    0    0    0    0  ...  0.10   
125968  8  udp   private   SF   105   145    0    0    0    0  ...  0.96   
125969  0  tcp      smtp   SF  2231   384    0    0    0    0  ...  0.12   
125970  0  tcp    klogin   S0     0     0    0    0    0    0  ...  0.03   
125971  0  tcp  ftp_data   SF   151     0    0    0    0    0  ...  0.30   

        0.03  0.17.1  0.00.6  0.00.7  0.00.8  0.05  0.00.9   normal  20  
0       0.60    0.88    0.00    0.00    0.00  0.00    0.00   normal  15  
1       0.05    0.00    0.00    1.00    1.00  0.00    0.00  neptune  19  
2       0.00    0.03    0.04    0.03    0.01  0.00    0.01   normal  21  
3       0.00    0.00    0.00    0.00    0.00  0.00    0.00   normal  21  
4       0.07    0.00    0.00    0.00    0.00  1.00    1.00  neptune  21  
...      ...     ...     ...     ...     ...   ...     ...      ...  ..  
125967  0.06    0.00    0.00    1.00    1.00  0.00    0.00  neptune  20  
125968  0.01    0.01    0.00    0.00    0.00  0.00    0.00   normal  21  
125969  0.06    0.00    0.00    0.72    0.00  0.01    0.00   normal  18  
125970  0.05    0.00    0.00    1.00    1.00  0.00    0.00  neptune  20  
125971  0.03    0.30    0.00    0.00    0.00  0.00    0.00   normal  21  

[125972 rows x 43 columns]

In [62]:
columns = (['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack'
,'level'])

df.columns = columns

In [63]:
#helper function for deeper analysis
def unique_values(df, columns):
    """Prints unique values and their counts for specific columns in the DataFrame."""

    for column_name in columns:
        print(f"Column: {column_name}\n{'-'*30}")
        unique_vals = df[column_name].unique()
        value_counts = df[column_name].value_counts()
        print(f"Unique Values ({len(unique_vals)}): {unique_vals}\n")
        print(f"Value Counts:\n{value_counts}\n{'='*40}\n")

In [64]:
cat_features = df.select_dtypes(include='object').columns
unique_values(df, cat_features)

Column: protocol_type
------------------------------
Unique Values (3): ['udp' 'tcp' 'icmp']

Value Counts:
protocol_type
tcp     102688
udp      14993
icmp      8291
Name: count, dtype: int64

Column: service
------------------------------
Unique Values (70): ['other' 'private' 'http' 'remote_job' 'ftp_data' 'name' 'netbios_ns'
 'eco_i' 'mtp' 'telnet' 'finger' 'domain_u' 'supdup' 'uucp_path' 'Z39_50'
 'smtp' 'csnet_ns' 'uucp' 'netbios_dgm' 'urp_i' 'auth' 'domain' 'ftp'
 'bgp' 'ldap' 'ecr_i' 'gopher' 'vmnet' 'systat' 'http_443' 'efs' 'whois'
 'imap4' 'iso_tsap' 'echo' 'klogin' 'link' 'sunrpc' 'login' 'kshell'
 'sql_net' 'time' 'hostnames' 'exec' 'ntp_u' 'discard' 'nntp' 'courier'
 'ctf' 'ssh' 'daytime' 'shell' 'netstat' 'pop_3' 'nnsp' 'IRC' 'pop_2'
 'printer' 'tim_i' 'pm_dump' 'red_i' 'netbios_ssn' 'rje' 'X11' 'urh_i'
 'http_8001' 'aol' 'http_2784' 'tftp_u' 'harvest']

Value Counts:
service
http         40338
private      21853
domain_u      9043
smtp          7313
ftp_data      6859
 

In [65]:
attack_n = []
for i in df.attack :
  if i == 'normal':
    attack_n.append("normal")
  else:
    attack_n.append("malicious")
df['attack'] = attack_n 

In [66]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
clm=['protocol_type', 'service', 'flag', 'attack']
for x in clm:
    df[x]=le.fit_transform(df[x])

In [67]:
from sklearn.model_selection import train_test_split

X = df.drop(["attack"], axis=1)
y = df["attack"]

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1,random_state=43) 

In [68]:
train_index = X_train.columns
train_index

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'level'],
      dtype='object')

In [69]:
from sklearn.feature_selection import mutual_info_classif
mutual_info = mutual_info_classif(X_train, y_train)
mutual_info = pd.Series(mutual_info)
mutual_info.index = train_index
mutual_info.sort_values(ascending=False)

src_bytes                      0.566417
service                        0.469278
dst_bytes                      0.441762
flag                           0.369764
same_srv_rate                  0.365033
diff_srv_rate                  0.361568
dst_host_srv_count             0.334602
dst_host_same_srv_rate         0.310758
logged_in                      0.291947
dst_host_serror_rate           0.286073
dst_host_diff_srv_rate         0.285632
dst_host_srv_serror_rate       0.280399
serror_rate                    0.277414
srv_serror_rate                0.268450
count                          0.266063
dst_host_srv_diff_host_rate    0.189012
level                          0.152561
dst_host_count                 0.142356
dst_host_same_src_port_rate    0.132373
srv_diff_host_rate             0.099436
srv_count                      0.063099
dst_host_srv_rerror_rate       0.062454
protocol_type                  0.054415
rerror_rate                    0.039478
srv_rerror_rate                0.037189


In [70]:
from sklearn.feature_selection import SelectKBest
Select_features = SelectKBest(mutual_info_classif, k=30)
Select_features.fit(X_train, y_train)
train_index[Select_features.get_support()]

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'wrong_fragment', 'hot', 'logged_in', 'num_access_files',
       'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate',
       'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
       'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
       'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate',
       'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'level'],
      dtype='object')

In [71]:
columns=['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'wrong_fragment', 'hot', 'logged_in', 'num_compromised',
       'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate']

#We will continue our model with top 15 features, because dataset is big enough

X_train=X_train[columns]
X_test=X_test[columns]

In [72]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) # we use only transform in order to prevent data leakage

In [73]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

In [74]:
XGBoost_model = XGBClassifier(random_state = 42)
Logistic_model = LogisticRegression(random_state=42)

In [75]:
rf_model=RandomForestClassifier(random_state=42)

In [76]:
XGBoost = XGBoost_model.fit(X_train,y_train)

In [77]:
Logistic = Logistic_model.fit(X_train,y_train)

c:\Users\kushal\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [78]:
rf=rf_model.fit(X_train,y_train)

In [79]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, recall_score, precision_score, f1_score, roc_auc_score

In [80]:
#it's a helper function in order to evaluate our model if it's overfit or underfit.
def eval_metric(model, X_train, y_train, X_test, y_test):
    y_train_pred = model.predict(X_train)
    y_pred = model.predict(X_test)
    
    print("Test_Set")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print()
    print("Train_Set")
    print(confusion_matrix(y_train, y_train_pred))
    print(classification_report(y_train, y_train_pred))

In [81]:
eval_metric(rf, X_train, y_train, X_test, y_test)

Test_Set
[[5818   10]
 [   8 6762]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5828
           1       1.00      1.00      1.00      6770

    accuracy                           1.00     12598
   macro avg       1.00      1.00      1.00     12598
weighted avg       1.00      1.00      1.00     12598


Train_Set
[[52768    34]
 [   23 60549]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     52802
           1       1.00      1.00      1.00     60572

    accuracy                           1.00    113374
   macro avg       1.00      1.00      1.00    113374
weighted avg       1.00      1.00      1.00    113374



In [82]:
eval_metric(Logistic_model, X_train, y_train, X_test, y_test)

Test_Set
[[5421  407]
 [ 233 6537]]
              precision    recall  f1-score   support

           0       0.96      0.93      0.94      5828
           1       0.94      0.97      0.95      6770

    accuracy                           0.95     12598
   macro avg       0.95      0.95      0.95     12598
weighted avg       0.95      0.95      0.95     12598


Train_Set
[[49317  3485]
 [ 2141 58431]]
              precision    recall  f1-score   support

           0       0.96      0.93      0.95     52802
           1       0.94      0.96      0.95     60572

    accuracy                           0.95    113374
   macro avg       0.95      0.95      0.95    113374
weighted avg       0.95      0.95      0.95    113374



In [83]:
eval_metric(XGBoost_model, X_train, y_train, X_test, y_test)

Test_Set
[[5818   10]
 [   9 6761]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5828
           1       1.00      1.00      1.00      6770

    accuracy                           1.00     12598
   macro avg       1.00      1.00      1.00     12598
weighted avg       1.00      1.00      1.00     12598


Train_Set
[[52751    51]
 [   29 60543]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     52802
           1       1.00      1.00      1.00     60572

    accuracy                           1.00    113374
   macro avg       1.00      1.00      1.00    113374
weighted avg       1.00      1.00      1.00    113374



In [84]:
param_grid = {
    "n_estimators": [50,64,100,128],
    "max_depth": [2, 3, 4,5,6],
    "learning_rate": [0.01,0,0.03, 0.05, 0.1],
    "subsample": [0.5, 0.8],
    "colsample_bytree": [0.5, 0.8]
}

In [85]:
# from sklearn.model_selection import GridSearchCV

# XGB_model = XGBClassifier(random_state=42) #initialize the model

# XGB_grid_model = GridSearchCV(XGB_model,
#                         param_grid,
#                         scoring="f1",
#                         n_jobs=-1,
#                         return_train_score=True).fit(X_train, y_train)

In [86]:
XGB_model = XGBClassifier(
    colsample_bytree=0.5,
    learning_rate=0.1,
    max_depth=6,
    n_estimators=128,
    subsample=0.8
)

# Fit the classifier to your data
XGB_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.5, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=128, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [87]:
y_pred = XGB_model.predict(X_test)
y_pred_proba = XGB_model.predict_proba(X_test)

xgb_f1 = f1_score(y_test, y_pred)
xgb_recall = recall_score(y_test, y_pred)
xgb_auc = roc_auc_score(y_test, y_pred_proba[:,1])

In [88]:
xgb_auc

0.9999819036911402

In [89]:
eval_metric(XGB_model, X_train, y_train, X_test, y_test)

Test_Set
[[5811   17]
 [   6 6764]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5828
           1       1.00      1.00      1.00      6770

    accuracy                           1.00     12598
   macro avg       1.00      1.00      1.00     12598
weighted avg       1.00      1.00      1.00     12598


Train_Set
[[52689   113]
 [   35 60537]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     52802
           1       1.00      1.00      1.00     60572

    accuracy                           1.00    113374
   macro avg       1.00      1.00      1.00    113374
weighted avg       1.00      1.00      1.00    113374



In [90]:
df1=pd.read_csv('C:/Users/kushal/Desktop/new_final_year/KDDTest+.txt/KDDTest+.txt')

In [91]:
df1

0   tcp   private   REJ    0.1    0.2  0.3  0.4  0.5  0.6  ...  0.04.1  \
0      0   tcp   private   REJ      0      0    0    0    0    0  ...    0.00   
1      2   tcp  ftp_data    SF  12983      0    0    0    0    0  ...    0.61   
2      0  icmp     eco_i    SF     20      0    0    0    0    0  ...    1.00   
3      1   tcp    telnet  RSTO      0     15    0    0    0    0  ...    0.31   
4      0   tcp      http    SF    267  14515    0    0    0    0  ...    1.00   
...   ..   ...       ...   ...    ...    ...  ...  ...  ...  ...  ...     ...   
22538  0   tcp      smtp    SF    794    333    0    0    0    0  ...    0.72   
22539  0   tcp      http    SF    317    938    0    0    0    0  ...    1.00   
22540  0   tcp      http    SF  54540   8314    0    0    0    2  ...    1.00   
22541  0   udp  domain_u    SF     42     42    0    0    0    0  ...    0.99   
22542  0   tcp    sunrpc   REJ      0      0    0    0    0    0  ...    0.08   

       0.06.1  0.00.3  0.00.4  0.00.5  0.00.6  1.00.2  1.00.3  neptune  21  
0        0.06    0.00    0.00    0.00     0.0    1.00    1.00  neptune  21  
1        0.04    0.61    0.02    0.00     0.0    0.00    0.00   normal  21  
2        0.00    1.00    0.28    0.00     0.0    0.00    0.00    saint  15  
3        0.17    0.03    0.02    0.00     0.0    0.83    0.71    mscan  11  
4        0.00    0.01    0.03    0.01     0.0    0.00    0.00   normal  21  
...       ...     ...     ...     ...     ...     ...     ...      ...  ..  
22538    0.06    0.01    0.01    0.01     0.0    0.00    0.00   normal  21  
22539    0.00    0.01    0.01    0.01     0.0    0.00    0.00   normal  21  
22540    0.00    0.00    0.00    0.00     0.0    0.07    0.07     back  15  
22541    0.01    0.00    0.00    0.00     0.0    0.00    0.00   normal  21  
22542    0.03    0.00    0.00    0.00     0.0    0.44    1.00    mscan  14  

[22543 rows x 43 columns]

In [92]:
columns = (['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack'
,'level'])

df1.columns = columns

In [93]:
df1['attack'].value_counts()

attack
normal             9711
neptune            4656
guess_passwd       1231
mscan               996
warezmaster         944
apache2             737
satan               735
processtable        685
smurf               665
back                359
snmpguess           331
saint               319
mailbomb            293
snmpgetattack       178
portsweep           157
ipsweep             141
httptunnel          133
nmap                 73
pod                  41
buffer_overflow      20
multihop             18
named                17
ps                   15
sendmail             14
rootkit              13
xterm                13
teardrop             12
xlock                 9
land                  7
xsnoop                4
ftp_write             3
worm                  2
loadmodule            2
perl                  2
sqlattack             2
udpstorm              2
phf                   2
imap                  1
Name: count, dtype: int64

In [94]:
attack_n = []
for i in df1.attack :
  if i == 'normal':
    attack_n.append("normal")
  else:
    attack_n.append("malicious")
df1['attack'] = attack_n 

In [95]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
clm=['protocol_type', 'service', 'flag', 'attack']
for x in clm:
    df1[x]=le.fit_transform(df1[x])

In [96]:
from sklearn.model_selection import train_test_split

X = df1.drop(["attack"], axis=1)
y = df1["attack"]

In [97]:
columns=['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'wrong_fragment', 'hot', 'logged_in', 'num_compromised',
       'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate']

#We will continue our model with top 15 features, because dataset is big enough

X=X[columns]


In [98]:
X

duration  protocol_type  service  flag  src_bytes  dst_bytes  \
0             0              1       45     1          0          0   
1             2              1       19     9      12983          0   
2             0              0       13     9         20          0   
3             1              1       55     2          0         15   
4             0              1       22     9        267      14515   
...         ...            ...      ...   ...        ...        ...   
22538         0              1       49     9        794        333   
22539         0              1       22     9        317        938   
22540         0              1       22     9      54540       8314   
22541         0              2       11     9         42         42   
22542         0              1       52     1          0          0   

       wrong_fragment  hot  logged_in  num_compromised  count  srv_count  \
0                   0    0          0                0    136          1   
1                   0    0          0                0      1          1   
2                   0    0          0                0      1         65   
3                   0    0          0                0      1          8   
4                   0    0          1                0      4          4   
...               ...  ...        ...              ...    ...        ...   
22538               0    0          1                0      1          1   
22539               0    0          1                0      2         11   
22540               0    2          1                1      5         10   
22541               0    0          0                0      4          6   
22542               0    0          0                0      4         10   

       serror_rate  srv_serror_rate  rerror_rate  
0              0.0             0.00          1.0  
1              0.0             0.00          0.0  
2              0.0             0.00          0.0  
3              0.0             0.12          1.0  
4              0.0             0.00          0.0  
...            ...              ...          ...  
22538          0.0             0.00          0.0  
22539          0.0             0.00          0.0  
22540          0.0             0.00          0.0  
22541          0.0             0.00          0.0  
22542          0.0             0.00          1.0  

[22543 rows x 15 columns]

In [99]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [100]:
X

array([[-0.15553762, -0.17630738,  0.93400235, ..., -0.34847667,
        -0.34739862,  1.83031738],
       [-0.15411633, -0.17630738, -0.88221042, ..., -0.34847667,
        -0.34739862, -0.5730277 ],
       [-0.15553762, -2.69500023, -1.30133645, ..., -0.34847667,
        -0.34739862, -0.5730277 ],
       ...,
       [-0.15553762, -0.17630738, -0.67264741, ..., -0.34847667,
        -0.34739862, -0.5730277 ],
       [-0.15553762,  2.34238546, -1.44104512, ..., -0.34847667,
        -0.34739862, -0.5730277 ],
       [-0.15553762, -0.17630738,  1.42298271, ..., -0.34847667,
        -0.34739862,  1.83031738]])

In [101]:
y_pred=Logistic.predict(X)

In [102]:
accuracy_score(y_pred,y)

0.7967883600230671

In [103]:
df1['attack'].value_counts()

attack
0    12832
1     9711
Name: count, dtype: int64

In [104]:
label_mapping = {label: code for code, label in enumerate(le.classes_)}
print("Label Mapping:", label_mapping)

Label Mapping: {'malicious': 0, 'normal': 1}


In [105]:
df1.head(5)

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0         0              1       45     1          0          0     0   
1         2              1       19     9      12983          0     0   
2         0              0       13     9         20          0     0   
3         1              1       55     2          0         15     0   
4         0              1       22     9        267      14515     0   

   wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0               0       0    0  ...                    0.00   
1               0       0    0  ...                    0.61   
2               0       0    0  ...                    1.00   
3               0       0    0  ...                    0.31   
4               0       0    0  ...                    1.00   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.06                         0.00   
1                    0.04                         0.61   
2                    0.00                         1.00   
3                    0.17                         0.03   
4                    0.00                         0.01   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00   
1                         0.02                  0.00   
2                         0.28                  0.00   
3                         0.02                  0.00   
4                         0.03                  0.01   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                       0.0                  1.00                      1.00   
1                       0.0                  0.00                      0.00   
2                       0.0                  0.00                      0.00   
3                       0.0                  0.83                      0.71   
4                       0.0                  0.00                      0.00   

   attack  level  
0       0     21  
1       1     21  
2       0     15  
3       0     11  
4       1     21  

[5 rows x 43 columns]

In [106]:
final_scaled_df = pd.DataFrame(X, columns=columns)
final_scaled_df['attack'] = y

In [107]:
final_scaled_df['attack'].value_counts()

attack
0    12832
1     9711
Name: count, dtype: int64

In [108]:
import pandas as pd
from sklearn.utils import shuffle

# Assuming df1 is already loaded with 'label' column containing 'normal' and 'malicious'
# Sample DataFrame df1 for the sake of the example
# df1 = pd.read_csv("your_existing_data.csv")

# Filter out "normal" and "malicious" rows
normal_df = final_scaled_df[final_scaled_df['attack'] == 1].head(500)  # First 1000 "normal"
malicious_df = final_scaled_df[final_scaled_df['attack'] ==0].head(15)  # First 100 "malicious"

# Concatenate both DataFrames
final_df = pd.concat([normal_df, malicious_df])

# Shuffle the DataFrame
shuffled_df = shuffle(final_df, random_state=42)  # Shuffle and reset index

# Save the shuffled DataFrame to a CSV file

shuffled_df['attack'].value_counts()
# print("CSV with shuffled data created successfully.")


attack
1    500
0     15
Name: count, dtype: int64

In [109]:
shuffled_df.to_csv('apple.csv', index=False)

In [110]:
shuffled_df

duration  protocol_type   service      flag  src_bytes  dst_bytes  \
671  -0.155538      -0.176307 -0.882210  0.662209   0.107664  -0.096898   
1102 -0.155538      -0.176307 -0.672647  0.662209  -0.021549  -0.088887   
963  -0.155538      -0.176307 -0.672647  0.662209  -0.021483  -0.020977   
353  -0.155538      -0.176307 -0.672647  0.662209  -0.021477   0.617310   
2    -0.155538      -2.695000 -1.301336  0.662209  -0.021946  -0.096898   
...        ...            ...       ...       ...        ...        ...   
167  -0.155538      -0.176307 -0.672647  0.662209  -0.021327   0.306414   
239  -0.154827      -0.176307  1.213420  0.662209  -0.019078  -0.080734   
580  -0.155538      -0.176307 -0.672647  0.662209  -0.021282  -0.083891   
952  -0.155538       2.342385  0.934002  0.662209  -0.021767  -0.090065   
228  -0.155538      -0.176307 -0.672647  0.662209  -0.021494  -0.060469   

      wrong_fragment       hot  logged_in  num_compromised     count  \
671        -0.059105 -0.113524  -0.890408        -0.016494 -0.552546   
1102       -0.059105 -0.113524   1.123081        -0.016494 -0.435847   
963        -0.059105 -0.113524   1.123081        -0.016494 -0.466966   
353        -0.059105 -0.113524   1.123081        -0.016494 -0.607006   
2          -0.059105 -0.113524  -0.890408        -0.016494 -0.607006   
...              ...       ...        ...              ...       ...   
167        -0.059105 -0.113524   1.123081        -0.016494 -0.552546   
239        -0.059105 -0.113524   1.123081        -0.016494 -0.607006   
580        -0.059105 -0.113524   1.123081        -0.016494 -0.591446   
952        -0.059105 -0.113524  -0.890408        -0.016494 -0.607006   
228        -0.059105 -0.113524   1.123081        -0.016494 -0.319147   

      srv_count  serror_rate  srv_serror_rate  rerror_rate  attack  
671   -0.259653    -0.348477        -0.347399    -0.573028       1  
1102  -0.091232    -0.348477        -0.347399    -0.573028       1  
963   -0.136144    -0.348477        -0.347399    -0.573028       1  
353   -0.270881    -0.348477        -0.347399    -0.573028       1  
2      0.380348    -0.348477        -0.347399    -0.573028       0  
...         ...          ...              ...          ...     ...  
167   -0.136144    -0.348477        -0.347399    -0.573028       1  
239   -0.327021    -0.348477        -0.347399    -0.573028       1  
580   -0.315793    -0.348477        -0.347399    -0.573028       1  
952   -0.338249    -0.348477        -0.347399    -0.573028       1  
228    0.077190    -0.348477        -0.347399    -0.573028       1  

[515 rows x 16 columns]

In [111]:
import joblib

# Save the model to a file
joblib.dump(Logistic, 'lgt_model.pkl')

print("Model saved successfully.")


Model saved successfully.


In [112]:
df1.shape

(22543, 43)